quintype/malibu

.circleci/config.yml, package.json
Added Circle CI integration for linting js and jsx files on a PR.
=> circle ci integration

package-lock.json, package.json
This fixes `found 154 vulnerabilities (1 low, 142 moderate, 11 high)`
=> changes made by - npm audit fix

package-lock.json, package.json, webpack.config.js
add webpack plugin webpack-common-shake
https://github.com/indutny/webpack-common-shake
this reduced the bundle size by 1.1kb
=> Commonjs tree shaking

package.json
will pass only modified files to linter, deleted files will be ignored
=> prevent deleted files from being passed to linter

app/server/load-data.js
These values are used by every app and should be in the Malibu.
=> social links, section and publisher name to app

app/isomorphic/components/pages/tag.js, app/isomorphic/constants.js, app/server/data-loaders/tag-page-data.js, app/server/routes.js, package-lock.json, package.json
For the ticket https://github.com/quintype/ace-support/issues/251, added the SEO meta data in tag page
=> Added the SEO metadata for tag page

package-lock.json, package.json
upgrade quintype-build package to use object spread operator. https://github.com/quintype/quintype-node-build/pull/11
=> upgrade build

app/assets/stylesheets/app.scss, app/isomorphic/components/story-templates/blank.js, package-lock.json, package.json
render youtube thumbnail and generate youtube iframe on click
Dependencies # quintype node components
manual test
=> update package and styling for youtube story element

package-lock.json, package.json
Updated the @quintype/framework version to v4.5.4 to test the new release for the browser back button issue
Fixes # (https://github.com/quintype/ace-planning/issues/91)
Dependencies # (dependency-issue-reference) 
=> fix:update the framework version

.circleci/config.yml
=> fix(add qa_testing env to lighthouse)

app/isomorphic/components/form/index.js, app/isomorphic/components/form/styles.m.css
Changed isolated bootstrap version from 4.0.0 to 4.1.0 in forms page
Fixes https://github.com/quintype/itsman/issues/6732
=> Changed isolated bootstrap version from 4.0.0 to 4.1.0 in forms page

app/isomorphic/components/story-grid.js, config/publisher.yml, lighthouserc.js, views/pages/layout.ejs
=> Remove gpt code

app/isomorphic/components/header/nav-bar/index.js, app/isomorphic/components/header/navbar-search/index.js, app/isomorphic/components/login/Modal/index.js, app/isomorphic/components/molecules/forms/forgot-password.js, app/isomorphic/components/molecules/forms/login.js, app/isomorphic/components/molecules/forms/otp.js, app/isomorphic/components/molecules/forms/sign-up.js, app/isomorphic/components/pages/catalog.js, app/isomorphic/components/pages/home.js
=> accessibility and alt attribute

app/assets/stylesheets/app.scss, app/isomorphic/components/breaking-news-view.js
=> Perf brk news

package-lock.json, package.json
=> fix: update custom timezone seo package

tutorial/preview.md
update story and home preview docs
Fixes: https://github.com/quintype/ace-planning/issues/268
Dependencies 
Documentation: https://developers.quintype.com/malibu/tutorial/preview.html
=> chore: update preview docs

Dockerfile, package-lock.json, package.json
The lhci install was in Docker. I had added this since I was facing some issue. But then this will delay the build. So moving this as a dev dependency.
Fixes: https://github.com/quintype/ace-planning/issues/303
Tested the circle ci.
=> fix(lhci): move to dev deps

app/isomorphic/components/header/nav-bar/index.js
Remove the user placeholder from navbar
=> fix(remove user placeholder)

package-lock.json, package.json
Fixes # (issue-reference) https://github.com/quintype/ace-planning/issues/316
Dependencies # (dependency-issue-reference) NA
Documentation # (link to the corresponding documentation changes) NA
Package update
=> Updated the  qt/components to the latest version

diff.sh
Just added the diff script, to push the changes to malibu-advanced. This may not be a complete solution. Feel free to add changes to this. This is just the initial script.
=> add diff script to ease pushing to malibu-advanced

app/isomorphic/component-bundles/home.js, app/isomorphic/component-bundles/list.js, app/isomorphic/pick-component.js
=> fix: create separate chunk for home and preview

app/client/render.js, app/isomorphic/components/layouts/footer/index.js, app/isomorphic/components/layouts/header/top-bar/index.js
Added hydration for app logo to fix ajax navigation issue
Fixes # https://github.com/quintype/ace-planning/issues/155
Dependencies # NA
Documentation # NA
=> Fix: Fix ajax navigation issue on clicking on app logo

tutorial/onesignal.md
=> docs: modify onesignal docs

app/isomorphic/components/get-collection-template.js, app/server/data-loaders/home-page-data.js, app/server/load-data.js, config/publisher.yml, package-lock.json, package.json
This is for setting the default collection item limit. The default limit will be set to all the child or nested collection items.
if storyLimits is not passed, it will fall back to this default limit. If we don't pass the default limit, it will fall back to 40
https://github.com/quintype/ace-planning/issues/379
Dependencies - https://github.com/quintype/quintype-node-backend/pull/50
Documentation  -  https://developers.quintype.com/malibu/tutorial/adding-default-limit-to-collections.html
=> feat: Default nested limit

app/server/data-loaders/home-page-data.js
https://github.com/quintype/ace-planning/issues/399
Home preview is not working 
Documentation - updating
=> fix(home desktop preview)

app/isomorphic/components/layouts/app-logo/index.js
We were using an image tag with a hardcoded staging pointed image URL which was affecting our lcp on prod. So we replaced the image tag with svg
=> fix: use svg instead of image for malibu logo

tutorial/adding-progressive-image-loading.md
=> update: progressive image loading docs

tutorial/support-svg-sprite.md
https://github.com/quintype/ace-planning/issues/454
=> doc(support svg sprite loader)

tutorial/custom-cache-ttl.md
Add comprehensive docs for setting custom cache ttl
=> docs: set custom cache ttl values

tutorial/onesignal.md
=> fix(update onesignal doc)

tutorial/prerequisites-from-the-customer.md
Update the doc - Prerequisites from the customer
=> docs(update) : Prerequisites from the customer

tutorial/adding-a-homepage-component.md, tutorial/adding-default-limit-to-collections.md, tutorial/amp-library-integration.md, tutorial/arrow-integration-malibu-advanced.md, tutorial/compile-custom-assets.md, tutorial/custom-seo.md, tutorial/formpage-component.md, tutorial/implementing-a-design-system.md, tutorial/integrating-login.md, tutorial/loadable-components.md, tutorial/loading-fonts.md, tutorial/pre-render.md, tutorial/preview.md, tutorial/redirect-url.md, tutorial/support-nested-collection-limit.md
=> docs(nav_order): fix nav order of chapters

.circleci/config.yml
=> ignore dependabot

app/server/app.js, package-lock.json
Generated all the SEO tags, structure data from quintype node SEO library.
Ticket - https://github.com/quintype/malibu/issues/838
=> Feat(SEO): generated seo tags and structure data from libraries

malibu-advanced.md
This PR includes the docs of Intro to Malibu advanced
=> docs(malibu-advanced): add basic docs for malibu advanced

package-lock.json, package.json
Ticket - https://github.com/quintype/ace-planning/issues/470
=> chore(deps): Bump @quintype/framework from 5.0.2 to 5.0.3

index.md, isomorphic-rendering.md, malibu-advanced.md, moving-parts.md, terminology.md, tutorial/getting-started.md
Description:
Went through the documentation and made the required changes.
[Ticket](https://github.com/quintype/ace-planning/issues/491)
=> Fix(Docs): Made changes to some files

tutorial/qlitics-integration.md
Created generic documentation for Qlitics integration and usage for Non-Malibu publishers
Ticket - https://github.com/quintype/ace-planning/issues/493
=> Feat(docs): Add Qlitics integration documentation

tutorial/implementing-focus-point-using-gumlet.md
=> fix(image URL) : add proper image url 

tutorial/custom-cache-ttl.md
=> fix(docs): update custom cache TTL

app/isomorphic/components/form/index.js, app/isomorphic/components/pages/form.js, app/isomorphic/components/story-templates/blank.js, package-lock.json, package.json
Ticket - https://github.com/quintype/ace-planning/issues/517
1. In this pr, removed unused dependencies. Ex -  `i`, `npm`, ` formiojs` and `gumlet.js`
2. Added condition in story hero image, if hero-s3-ky not present , don't show hero image
=> Fix(dep):  Removed unused dependencies from package and hide hero image if s3 key not present on story page.

tutorial/best-practices.md
Added Documentation for Accessibility best practices
Reference: https://github.com/quintype/ace-planning/issues/539
=> Accessibility best practices

tutorial/service-worker-updates.md
Added docs for service worker updates.
Ticket - https://github.com/quintype/quintype-node-framework/issues/201
=> Updates service worker documentation

.circleci/config.yml
To Do after merge: make `@circleci-checks/perf_lighthouse_test` as `required`, remove stg
=> workflow changes

.circleci/config.yml
https://github.com/quintype/ace-planning/issues/547
=> Optimize CI usage

tutorial/how-to-add-a-new-schema.md
=> fix(How to add custom schema markup)

tutorial/how-to-add-a-new-schema.md, tutorial/how-to-override-author-url.md
Fix https://github.com/quintype/ace-planning/issues/579
=> Doc(How to override author url in person schema)

app/server/app.js, package-lock.json, package.json
Reference: https://github.com/quintype/ace-planning/issues/710
=> feat: remove powered by quintype from the footer

package-lock.json, package.json
Reference: https://github.com/quintype/quintype-amp/issues/398
=>  add height and width to amp-video to remove amp validation errors

tutorial/watermark-hero-image.md
Add watermark feature in Malibu-Adv
https://github.com/quintype/ace-planning/issues/754
=> Add. watermark documentation
